### ISSUE TITLE
Implementazione Enum

### ISSUE THREAD

**Issue by GuoLozZz** [UniPd-Programmazione-Borgo-Bislacco/Prova-Intermedia-2023-2024#1]
Durante la compilazione di Date.cpp il compilatore mi ha segnalato 40 errori su qualsiasi cosa riguardava month, penso sia dovuto ad Enum, forse non l'ho implementato correttamente.
Qua sotto qualche esempio di errore:

Date.h:7:19: error: 'Month' has not been declared
    7 |     Date (int yy, Month mm, int dd);
      |                   ^~~~~
Date.h:12:5: error: 'Month' does not name a type
   12 |     Month month() const;
      |     ^~~~~
Date.h:17:5: error: 'Month' does not name a type
   17 |     Month m;
      |     ^~~~~
Date.cpp:3:1: error: no declaration matches 'Date::Date(int, Month, int)'
    3 | Date::Date (int yy, Month mm, int dd)
      | ^~~~

**Comment by Heldingar** [comment]
perché devi fare Date::Month penso.
Invece era via del `enum class` invece dell' `enum` base e per la definizione messa in fondo
